debug: true

server:
  #port: 9090
  servlet:
    context-path: /

logging:
  level:
    ROOT: INFO
    com.kubewarrior: DEBUG
    org.springframework.security: DEBUG
    org.springframework: DEBUG

spring:
  # data:
  #   rest:
  #     defaultMediaType: "application/json"
  application:
    name: checkout
  sleuth:
    sampler:
      percentage: 1
    zipkin:
      base-url: http://localhost:9411/
  datasource:
    url: jdbc:mariadb://localhost:3306/checkout
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDBDialect
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://localhost:9080/auth/realms/micro-auth
#           jwk-set-uri: http://localhost:9080/auth/realms/micro-auth/protocol/openid-connect/certs