logging:
  level:
    org.springframework: WARN

spring:
  datasource:
    url: jdbc:mariadb://checkout-db:3306/checkout
    password: ${DB_ROOT_PASS}
  zipkin:
    base-url: http://zipkin.monitoring:9411/
  kafka:
    consumer:
      bootstrap-servers: kafka.default:9092

client:
  url: https://www.dh4r4pvj.ga

store:
  url: https://store.dh4r4pvj.ga