logging:
  level:
    org.springframework: WARN

spring:
  datasource:
    url: jdbc:mariadb://checkout-db:3306/checkout
    password: ${DB_ROOT_PASS}

client:
  url: http://dh4r4pvj.ga

store:
  url: http://store.dh4r4pvj.ga